// This file is part of RaSt mod_ecl.
//
// RaSt mod_ecl is  an extension module for the Apache  HTTP Server.  It enables
// the Apache HTTP  Server to run scripts written in  the Embeddable Common-Lisp
// language.
//
// Copyright (c) 2021 Ralf Stephan (RaSt) <me@ralf-stephan.name>
//
// RaSt mod_ecl is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either  version 3 of the  License, or (at your  option) any later
// version.
//
// RaSt mod_ecl is distributed  in the hope that it will  be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR  A PARTICULAR  PURPOSE.   See the  GNU General  Public  License for  more
// details.
//
// You should have received a copy of  the GNU General Public License along with
// RaSt     mod_ecl     in     the     file    COPYING.      If     not,     see
// <https://www.gnu.org/licenses/>.



/*
**  mod_ecl.c -- Apache sample ecl module
**  [Autogenerated via ``apxs -n ecl -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory
**  by running:
**
**    $ apxs -c -i mod_ecl.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /ecl in as follows:
**
**    #   apache2.conf
**    LoadModule ecl_module modules/mod_ecl.so
**    <Location /ecl>
**    SetHandler ecl
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /ecl and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/ecl
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**
**    The sample page from mod_ecl.c
*/



/**
 * @mainpage RaSt mod_ecl
 *
 * RaSt mod_ecl is  an extension module for the Apache  HTTP Server.  It enables
 * the Apache HTTP  Server to run scripts written in  the Embeddable Common-Lisp
 * language.
 *
 * Copyright (c) 2021 Ralf Stephan (RaSt)
 * <[mailto:me@ralf-stephan.name](mailto:me@ralf-stephan.name)>
 *
 * RaSt mod_ecl is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either  version 3 of the  License, or (at your  option) any later
 * version.
 *
 * RaSt mod_ecl is distributed  in the hope that it will  be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR  A PARTICULAR  PURPOSE.   See the  GNU General  Public  License for  more
 * details.
 *
 * You should have received a copy of  the GNU General Public License along with
 * RaSt     mod_ecl     in     the     file    COPYING.      If     not,     see
 * <[https://www.gnu.org/licenses/](https://www.gnu.org/licenses/)>.
 *
 * @tableofcontents
 */



/**
 * @file mod_ecl.c
 *
 * @brief This file contains the core functionality of this module.
 *
 * @details
 */



#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

#include "mod_ecl.h"



/* The sample content handler */
static int ecl_handler(request_rec *r)
{
    if (strcmp(r->handler, "application/x-httpd-ecl")) {
        return DECLINED;
    }
    r->content_type = "text/html";

    if (!r->header_only)
        ap_rputs("The sample page from mod_ecl.c\n", r);
    return OK;
}



/**
 * @brief Table of config file commands. / Any directives we may have for httpd.
 *
 * @details
 *
 * List the configuration directives we want to register with the server.
 *
 * Register directives with:
 *
 * * [AP_TAKE_ARGV](https://ci.apache.org/projects/httpd/trunk/doxygen/group__APACHE__CORE__CONFIG.html#gaeafa400a7c6388b13a38d469f6cbca4a)
 *   This configuration directive will handle its own parsing of arguments.
 *
 * * [AP_TAKE1](https://ci.apache.org/projects/httpd/trunk/doxygen/group__APACHE__CORE__CONFIG.html#ga1f074abcaa85b893817adee6ea2dc816)
 *   This configuration directive takes 1 argument.
 *
 * * [AP_TAKE2](https://ci.apache.org/projects/httpd/trunk/doxygen/group__APACHE__CORE__CONFIG.html#gab5ae54825b0b4b414b21bbd619e6c092)
 *   This configuration directive takes 2 argument.
 *
 * * [AP_TAKE3](https://ci.apache.org/projects/httpd/trunk/doxygen/group__APACHE__CORE__CONFIG.html#gaacf930c9d842396ad08f860e3f25b9ec)
 *   This configuration directive takes 3 argument.
 *
 * @see [Apache HTTP Server --- Core routines --- Configuration](https://ci.apache.org/projects/httpd/trunk/doxygen/group__APACHE__CORE__CONFIG.html)
 */

static const command_rec config_file_commands[] =
{
  {NULL}
};


  
/**
 * @brief Register hooks. / Our hook registering function.
 *
 * @details
 *
 * A hook to allow  modules to hook other points in  the request processing.  In
 * this function, modules  should call the ap_hook_*() functions  to register an
 * interest in a specific step in processing the current request.
 *
 * Available hooks functions:
 *
 * * ap_hook_access_checker
 *
 * * ap_hook_access_checker_ex
 *
 * * ap_hook_auth_checker
 *
 * * ap_hook_check_config
 *
 * * ap_hook_check_user_id
 *
 * * ap_hook_child_init
 *
 * * ap_hook_child_status
 *
 * * ap_hook_create_connection
 *
 * * ap_hook_create_request
 *
 * * ap_hook_default_port
 *
 * * ap_hook_dirwalk_stat
 *
 * * ap_hook_drop_privileges
 *
 * * ap_hook_end_generation
 *
 * * ap_hook_error_log
 *
 * * ap_hook_expr_lookup
 *
 * * ap_hook_fatal_exception
 *
 * * ap_hook_fixups
 *
 * * ap_hook_force_authn
 *
 * * ap_hook_generate_log_id
 *
 * * ap_hook_get_mgmt_items
 *
 * * ap_hook_get_suexec_identity
 *
 * * ap_hook_handler
 *
 * * ap_hook_header_parser
 *
 * * ap_hook_http_scheme
 *
 * * ap_hook_insert_error_filter
 *
 * * ap_hook_insert_filter
 *
 * * ap_hook_insert_network_bucket
 *
 * * ap_hook_log_transaction
 *
 * * ap_hook_map_to_storage
 *
 * * ap_hook_monitor
 *
 * * ap_hook_mpm
 *
 * * ap_hook_mpm_get_name
 *
 * * ap_hook_mpm_query
 *
 * * ap_hook_mpm_register_timed_callback
 *
 * * ap_hook_note_auth_failure
 *
 * * ap_hook_open_htaccess
 *
 * * ap_hook_open_logs
 *
 * * ap_hook_optional_fn_retrieve
 *
 * * ap_hook_optional_hook_test
 *
 * * ap_hook_post_config
 *
 * * ap_hook_post_perdir_config
 *
 * * ap_hook_post_read_request
 *
 * * ap_hook_pre_close_connectio
 *
 * * ap_hook_pre_config
 *
 * * ap_hook_pre_connection
 *
 * * ap_hook_pre_mpm
 *
 * * ap_hook_pre_read_request
 *
 * * ap_hook_process_connection
 *
 * * ap_hook_protocol_get
 *
 * * ap_hook_protocol_propose
 *
 * * ap_hook_protocol_switch
 *
 * * ap_hook_quick_handler
 *
 * * ap_hook_resume_connection
 *
 * * ap_hook_ssl_add_cert_files
 *
 * * ap_hook_ssl_add_fallback_cert_files
 *
 * * ap_hook_ssl_answer_challenge
 *
 * * ap_hook_ssl_conn_is_ssl
 *
 * * ap_hook_ssl_ocsp_get_resp_hook
 *
 * * ap_hook_ssl_ocsp_prime_hook
 *
 * * ap_hook_ssl_var_lookup
 *
 * * ap_hook_suspend_connection
 *
 * * ap_hook_test_config
 *
 * * ap_hook_translate_name
 *
 * * ap_hook_type_checker
 *
 * @see [Apache HTTP Server --- Core routines --- Apache Hooks](https://ci.apache.org/projects/httpd/trunk/doxygen/group__hooks.html)
 *
 * @see [ap_expr.h](httpd-2.4.48\include\ap_expr.h)
 * @see [ap_hooks.h](httpd-2.4.48\include\ap_hooks.h)
 * @see [ap_mpm.h](httpd-2.4.48\include\ap_mpm.h)
 * @see [http_config.h](httpd-2.4.48\include\http_config.h)
 * @see [http_connection.h](httpd-2.4.48\include\http_connection.h)
 * @see [http_core.h](httpd-2.4.48\include\http_core.h)
 * @see [http_log.h](httpd-2.4.48\include\http_log.h)
 * @see [http_protocol.h](httpd-2.4.48\include\http_protocol.h)
 * @see [http_request.h](httpd-2.4.48\include\http_request.h)
 * @see [http_ssl.h](httpd-2.4.48\include\http_ssl.h)
 * @see [mpm_common.h](httpd-2.4.48\include\mpm_common.h)
 * @see [scoreboard.h](httpd-2.4.48\include\scoreboard.h)
 * @see [mod_optional_hook_export](httpd-2.4.48\modules\test\mod_optional_hook_export.h)
 * @see [unixd.h](httpd-2.4.48\os\unix\unixd.h)
 *
 * @param[in] pool
 *   This is the pool to use for all allocations.
 *
 * @return void
 */

static void register_hooks(apr_pool_t * pool)
{
    ap_hook_handler(ecl_handler, NULL, NULL, APR_HOOK_MIDDLE);
}



/**
 * @brief Register mod_ecl as Apache HTTP Server module.
 *
 * @details
 *
 * This is for setting up configuration handlers and directives.
 *
 * AP_MODULE_DECLARE_DATA  ---  Apache  Core  dso variables  are  declared  with
 *   AP_MODULE_DECLARE_DATA.   This  assures   the  appropriate  indirection  is
 *   invoked at compile time.   Symbols declared with AP_MODULE_DECLARE_DATA are
 *   always exported.
 *
 * Dispatch list for API hooks:
 *
 * * STANDARD20_MODULE_STUFF ---  Use this  in all standard  modules. /  FIll in
 *   with boilerplate code to make this module a standard 2.x module.
 *
 * * per_directory_configuration_handler    ---   Per-directory    configuration
 *   handler. / Create per-directory config structures.
 *
 * * per_directory_configuration_merge_handler  --- Per-directory  configuration
 *   merge handler. / Merge per-directory config structures.
 *
 * * per_server_configuration_handler ---  Per-server configuration  handler.  /
 *   Create per-server config structures.
 *
 * * per_server_configuration_merge_handler  --- Per-server  configuration merge
 *   handler. / Merge per-server config structures.
 *
 * * config_file_commands --- Table of config file commands. / Any directives we
 *   may have for httpd.
 *
 * * register_hooks --- Register hooks. / Our hook registering function.
 *
 * @code{.c}typedef struct module_struct module@endcode
 *
 * module_struct Data Fields:
 *
 * * version  ---  API  version,  not  module  version;  check  that  module  is
 *   compatible with this version of the server.
 *
 * * minor_version --- API minor version.   Provides API feature milestones. Not
 *   checked during module init.
 *
 * * module_index --- Index to this modules structures in config vectors.
 *
 * * name --- The name of the module's C file.
 *
 * * dynamic_load_handle --- The handle for the DSO.  Internal use only.
 *
 * * next --- A pointer to the next module in the list.
 *
 * * magic  ---  Magic Cookie  to  identify  a  module structure.   It's  mainly
 *   important for the DSO facility (see also mod_so).
 *
 * * rewrite_args --- Function to allow MPMs to re-write command line arguments.
 *   This hook is only available to MPMs.
 *
 * * create_dir_config --- Function to allow all modules to create per directory
 *   configuration structures.
 *
 * * merge_dir_config  ---  Function to  allow  all  modules  to merge  the  per
 *   directory configuration structures for two directories.
 *
 * * create_server_config --- Function to allow all modules to create per server
 *    configuration structures.
 *
 * * merge_server_config  --- Function  to allow  all modules  to merge  the per
 *   server configuration structures for two servers.
 *
 * * cmds ---  A command_rec  table that  describes all  of the  directives this
 *   module defines.
 *
 * * register_hooks ---  A hook  to allow  modules to hook  other points  in the
 *   request processing.  In this function,  modules should call the ap_hook_*()
 *   functions to  register an  interest in  a specific  step in  processing the
 *   current request.
 *
 * * flags --- A bitmask of AP_MODULE_FLAG_*.
 *
 * @see [Apache HTTP Server --- Core routines --- Configuration](https://ci.apache.org/projects/httpd/trunk/doxygen/group__APACHE__CORE__CONFIG.html)
 *
 * @see [Apache HTTP Server --- Core routines --- Configuration - module_struct Struct Reference](https://ci.apache.org/projects/httpd/trunk/doxygen/structmodule__struct.html)
 *
 * @see [ap_config.h File Reference](https://ci.apache.org/projects/httpd/trunk/doxygen/ap__config_8h.html)
 * @see [ap_config.h](file://httpd-2.4.48/include/ap_config.h)
 *
 * @see [http_config.h File Reference](https://ci.apache.org/projects/httpd/trunk/doxygen/http__config_8h.html)
 * @see [http_config.h](httpd-2.4.48/include/http_config.h)
 *
 * @see [macros.h File Reference](https://ci.apache.org/projects/httpd/trunk/doxygen/macros_8h.html)
 * @see [macros.h](file://httpd-2.4.48/include/macros.h)
 */

module AP_MODULE_DECLARE_DATA ecl_module =
{
  STANDARD20_MODULE_STUFF, // STANDARD20 MODULE STUFF
  NULL,                    // Per-directory configuration handler.
  NULL,                    // Per-directory configuration merge handler.
  NULL,                    // Per-server configuration handler.
  NULL,                    // Per-server configuration merge handler.
  config_file_commands,    // Config file Commands.
  register_hooks           // Register hooks.
};
